
tst_so~1: tst_so~1.o psg.o raster.o font.o time.o music.o effects.o
	cc68x -g tst_so~1.o psg.o raster.o font.o time.o music.o effects.o -o tst_so~1

tst_so~1.o: tst_so~1.c psg.h raster.h time.h effects.h
	cc68x -g -c tst_so~1.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c

raster.o: raster.c raster.h font.h
	cc68x -g -c raster.c

font.o: font.c font.h
	cc68x -g -c font.c

music.o: music.c music.h psg.h
	cc68x -g -c music.c

time.o: time.c time.h
	cc68x -g -c time.c

effects.o: effects.c effects.h psg.h
	cc68x -g -c effects.c
